version: '3'
services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/src
    depends_on:
      - migration
    environment:
      - DB_HOST=db
      - DB_USER=gino
      - APP_HOST=0.0.0.0
      - APP_PORT=80
    command: /env/bin/python run.py
  migration:
    build: .
    volumes:
      - .:/src
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=gino
    command: /env/bin/alembic upgrade head
  db:
    image: postgres
    environment:
      - POSTGRES_USER=gino
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
